### ISSUE TITLE
Closing Tool Window

### ISSUE THREAD

**Issue by mrclrchtr** [Quboid/NetworkAnarchy#16]
I have almost the same problem as @redaha71 described here:

> Is there a way to force the toolbar to stay open? When I click the roads menu the toolbar opens, when I select a road the toolbar closes, and there is no mod button to open it back up. I have to close the road menu then open it again to get toolbar which adds a rediculous amount of extra clicks while playing. I dont see a hotkey in options just to open the toolbar.

In my case, the toolbox also disappears in other cases, such as when I select a different elevation option.

This ist the Debug log of NetworkAnarchy:

> [Info] 0.0000558 | NetworkAnarchy v3.0.8.33201
[Info] 0.0040874 | [NA09] NetworkAnarchy: Network Skins not found
[Info] 0.0046290 | [NA05] NetworkAnarchy: Network Multitool failed loading
[Info] 0.0050349 | [NA03] NetworkAnarchy: Zoning Adjuster loaded
[Error] 0.0877116 | [NA24] Upgrade button template not found
[Info] 0.1022105 | [NA36] Registered networks: 1757
[Info] 0.1083958 | [NA22] NetworkAnarchy Initialized
[Debug] 2,547.5493419 | [NA29] Activated (Oneway Train Track (NetInfo))
   at NetworkAnarchy.NetworkAnarchy.Activate(.NetInfo info)
   at NetworkAnarchy.NetworkAnarchy.NetworkAnarchy.NetworkAnarchy.FpsBoosterUpdate_Patch0(NetworkAnarchy.NetworkAnarchy )
   at BehaviourUpdater.Utils.SafelyIterableList`1[[UnityEngine.MonoBehaviour, UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].CallUpdate()
   at BehaviourUpdater.Updater.Update()
[Debug] 2,547.5774777 | [NA38] Button parent is null (m_parent is OptionsBar (ColossalFramework.UI.UIPanel))
[Debug] 2,548.0035210 | [NA29] Activated (Train Track (NetInfo))
   at NetworkAnarchy.NetworkAnarchy.Activate(.NetInfo info)
   at NetworkAnarchy.NetworkAnarchy.NetworkAnarchy.NetworkAnarchy.FpsBoosterUpdate_Patch0(NetworkAnarchy.NetworkAnarchy )
   at BehaviourUpdater.Utils.SafelyIterableList`1[[UnityEngine.MonoBehaviour, UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].CallUpdate()
   at BehaviourUpdater.Updater.Update()
[Debug] 2,548.0231401 | [NA38] Button parent is null (m_parent is OptionsBar (ColossalFramework.UI.UIPanel))
[Debug] 2,549.8072459 | [NA38] Button parent is null (m_parent is OptionsBar (ColossalFramework.UI.UIPanel))
[Debug] 2,627.6206887 | [NA29] Activated (Oneway Train Track (NetInfo))
   at NetworkAnarchy.NetworkAnarchy.Activate(.NetInfo info)
   at NetworkAnarchy.NetworkAnarchy.NetworkAnarchy.NetworkAnarchy.FpsBoosterUpdate_Patch0(NetworkAnarchy.NetworkAnarchy )
   at BehaviourUpdater.Utils.SafelyIterableList`1[[UnityEngine.MonoBehaviour, UnityEngine, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].CallUpdate()
   at BehaviourUpdater.Updater.Update()
[Debug] 2,627.6410661 | [NA38] Button parent is null (m_parent is OptionsBar (ColossalFramework.UI.UIPanel))
[Debug] 2,629.4634240 | [NA38] Button parent is null (m_parent is OptionsBar (ColossalFramework.UI.UIPanel))

The last lines in output_log:

> 2,718,825ms | AdaptiveRoads | [Debug]  2,718,825ms | ANImplementation.get_Enabled() -> False
2,718,830ms | AdaptiveRoads | [Debug]  2,718,830ms | ANImplementation.get_Enabled() -> False
2,719,279ms | AdaptiveRoads | [Debug]  2,719,279ms | ANImplementation.get_Enabled() -> False
2,719,284ms | AdaptiveRoads | [Debug]  2,719,284ms | ANImplementation.get_Enabled() -> False
2,798,888ms | AdaptiveRoads | [Debug]  2,798,888ms | ANImplementation.get_Enabled() -> False
2,798,901ms | AdaptiveRoads | [Debug]  2,798,901ms | ANImplementation.get_Enabled() -> False

Thank you very much for your effort.

**Comment by Quboid** [comment]
Thank you for the report. This is a known issue that I would love to get to the bottom of. It is supposed to stay open when you have any network selected (and also while using Network Multitool or Zoning Adjuster).

How often does this happen? If it is not all the time, do you know what steps you can do to get this issue to happen?

I see you have debug logging on, that's good. The "Button parent is null (m_parent is OptionsBar (ColossalFramework.UI.UIPanel))" lines are probably related to this issue. Can you also send your full output_log.txt file and the output from Compatibility Report?

Like I said, I would love to solve this and I greatly appreciate any more help you can give me.

**Comment by mrclrchtr** [comment]
I could not reproduce it today :( 
Which is good and bad at the same time :D 
As soon as it occurs again, I'll try to find out more.

**Comment by kevinlaw91** [comment]
Hi @Quboid, thank for your time. Maybe you can take a look at klyte45/CS-FineRoadTool#8. I'm sure its the same bug that persisted from the original mod. Thanks

**Comment by caddywonkus** [comment]
[NetworkAnarchy.log](https://github.com/Quboid/NetworkAnarchy/files/9942947/NetworkAnarchy.log)

**Comment by caddywonkus** [comment]
Hello, @Quboid. I hope you didn't take my comment as any kind of complaint or demand. I seriously admire your work and am very grateful for the mods I... I just can't imagine enjoying this game without 'em! Thank you!!

I've worked in IT as a senior-level DBA for the past 25+ years, much of it in large enterprises. Most of my work just draws on experience to keep things running smooth and prevent or fix normal problems. But in terms of time spent, I make probably make more of a living troubleshooting weird things.

For a game... well, usually I either figure it out myself, or enough other people have the same problem I just have to wait for an update, so I usually stay quiet when I have a problem with a mod. This time though, well I saw you express somewhere having trouble with this bug, and not everyone seems to have it.  And I know from my own job how frustrating it can be to troubleshoot something that you just can't seem to reproduce reliably. I can, so I hope I can help here.

I whittled my problem down to the following mods (in addition to the default ones, plus this and Harmony of course). All were included, and all but "Hard Mode" were enabled:
- Load Order Mod (and Patch Loader - a dependency): so I can exclude mods, not just disable them, without having to re-sub them all; I usually use a lot more than this list
- Network MultiTool
- Picker
- FPS Booster+
- Unified UI++

FPS Booster: with everything else above, this is the one mod I can exclude and the issue disappears; include it and NA disappears. I've had this mod since October though. The issue only started happening after the update to NA back on Nov 4. It was the only change - I did not add/remove/reconfigure any other mods, just the update to this one. But I'm pretty sure FPS Booster is what it's conflicting with. Honestly I can do without, not really even sure why I have it to begin with. Just reading the description of it... "rename methods of base class." Yeah, as a DBA that's the kind of thing I've blocked projects over. But this is a game on a pc, not a massive database on a server worth more than my house. :)

Unified UI: this might be a factor. NA activates when the road menu is opened, naturally. Well, without Unified UI you can't open the MultiTool without opening the road menu first. With it, you can. And that's how I reproduce the issue - Multitool open  without the road menu, then use Picker.

I'm attaching a new debug log from NA. This time with just the mods above, including FPS Booster. I deleted the existing one first, so this one captures just start game, reproduce bug, close game (I also hate sifting through bloated logs full of a billion normal things ;) ). I watched the log file as I was going, too - up to about line 84 everything was fine. After that is when the disappearing starts.

I hope this helps! And again, thank you for these awesome mods! If I can help troubleshoot any further just let me know.

[NetworkAnarchy.log](https://github.com/Quboid/NetworkAnarchy/files/9945442/NetworkAnarchy.log)

**Comment by Quboid** [comment]
That you @caddywonkus , I appreciate all feedback. I have rolled back the latest change I made, and I will dive into your log to see if I can develop a reliable fix.

**Comment by ClipLee** [comment]
> Can you also send your full output_log.txt file and the output from Compatibility Report?

I was able to reproduce this bug.  It does not occur always but when it does, I have to restart the game to make it work again.
Everything seems to work fine, you open roads menu, there is the toolbar, then you hit _upgrade road_ tool and the toolbar is gone. I must switch again to any other road for it to appear again.

My output.log, Compatibility Report and NA log attached.
[output_log.txt](https://github.com/Quboid/NetworkAnarchy/files/11099231/output_log.txt)
[CompatibilityReport.log](https://github.com/Quboid/NetworkAnarchy/files/11099237/CompatibilityReport.log)
[NetworkAnarchy.log](https://github.com/Quboid/NetworkAnarchy/files/11099261/NetworkAnarchy.log)
